### ISSUE TITLE
Parsing stops after garbage line

### ISSUE THREAD

**Issue by EmiliaPaz** [EmiliaPaz/Arboretum#20]
After a garbage line is written, the parse stops reading whatever comes afterwards. For example, after the lambda function, it does not read b a and garbage, and therefore x = 1 + 2 is not parsed and rendered:
```
x = 1 + 2
b = \ x -> x + 1
b a
garbage
x = 1 + 2
```

**Comment by alexshadley** [comment]
Aha, good catch!  I think the current implementation will crash and return nothing any time we have a single invalid line.  I'll try to put out a fix for this pretty quickly.
